use_frameworks!

target 'SwiftDebugLog_Example' do
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Fabric', '~> 1.9.0'
  pod 'SwiftDebugLog', :path => '../'

  target 'SwiftDebugLog_Tests' do
    inherit! :search_paths

  end

  pre_install do |installer|
    # workaround for CocoaPods/CocoaPods#3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
end
